// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLs3Xjgngy92xho4T2k4BzogGi89-qTHE',
    appId: '1:121614191055:web:c2aa45182355dac07c2aba',
    messagingSenderId: '121614191055',
    projectId: 'studyhall-3ad22',
    authDomain: 'studyhall-3ad22.firebaseapp.com',
    storageBucket: 'studyhall-3ad22.appspot.com',
    measurementId: 'G-CCRHR49RW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDnIGMCOD3ti-lODL_ijVHXK0IqeNTXpg',
    appId: '1:121614191055:android:484fbe3b66d3d4967c2aba',
    messagingSenderId: '121614191055',
    projectId: 'studyhall-3ad22',
    storageBucket: 'studyhall-3ad22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSFewbDfrnFqGDQ7DOm59Ue_bnnHNHLVk',
    appId: '1:121614191055:ios:0c523a3e9be49a317c2aba',
    messagingSenderId: '121614191055',
    projectId: 'studyhall-3ad22',
    storageBucket: 'studyhall-3ad22.appspot.com',
    iosBundleId: 'com.example.studyhall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSFewbDfrnFqGDQ7DOm59Ue_bnnHNHLVk',
    appId: '1:121614191055:ios:a03576d457fa91ed7c2aba',
    messagingSenderId: '121614191055',
    projectId: 'studyhall-3ad22',
    storageBucket: 'studyhall-3ad22.appspot.com',
    iosBundleId: 'com.example.studyhall.RunnerTests',
  );
}
